
# Doc: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/buttress"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    target-branch: "main"
    assignees:
      - "mangirish1999"
      - "Tushar981"
      - "divishtk"
      
  - package-ecosystem: npm
    directory: "/protege"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: "main"
    assignees:
      - "NevetsKuro"
      
