
# Doc: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/buttress"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "NevetsKuro"
    assignees:
      - "mangirish1999"
      - "Tushar981"
      - "divishtk"
      
  - package-ecosystem: npm
    directory: "/protege"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"
    reviewers:
      - "NevetsKuro"
    assignees:
      - "NevetsKuro"
      
