/* eslint-disable jsx-a11y/no-static-element-interactions */
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Calendar, Star } from 'react-feather';
import LoadingMessage from '../components/loading';
import Header from '../components/Header';
import styles from '../styles/Browse.module.css';

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [starsFilter, setStarsFilter] = useState('All');
  const [costFilter, setCostFilter] = useState('All');
  const [amenitiesFilter, setAmenitiesFilter] = useState('All');
  const [memberFilter, setMemberFilter] = useState('All');
  const [locationFilter, setLocationFilter] = useState('All');

  const [hotels] = useState([
    {
      _id: '820ajn1k123askn90',
      hotelName: 'GRAND HILTON HOTEL',
      viewAmenities:
        'Half-Board/ All Inclusive + Complimentary Activities + Child Stays Free',
      stars: 2,
      rating: 4.5,
      location: 'MUMBAI',
      member: '10-20',
      cost: 5,
    },
    {
      _id: '821ajn1k123askn90',
      hotelName: 'GRAND HILTON HOTEL 2',
      viewAmenities:
        'Half-Board/ All Inclusive + Complimentary Activities + Child Stays Free',
      stars: 4,
      rating: 2.5,
      location: 'PUNE',
      member: '5-10',
      cost: 3,
    },
    {
      _id: '822ajn1k123askn90',
      hotelName: 'GRAND HILTON HOTEL 3',
      viewAmenities:
        'Half-Board/ All Inclusive + Complimentary Activities + Child Stays Free',
      stars: 5,
      rating: 5,
      location: 'JAIPUR',
      member: '1-4',
      cost: 2,
    },
  ]);

  const [cities] = useState([
    {
      _id: '120ajn1k123askn90',
      cityName: 'MUMBAI',
    },
    {
      _id: '121ajn1k123askn90',
      cityName: 'JAIPUR',
    },
    {
      _id: '122ajn1k123askn90',
      cityName: 'CHENNAI',
    },
    {
      _id: '123ajn1k123askn90',
      cityName: 'BANGALORE',
    },
    {
      _id: '124ajn1k123askn90',
      cityName: 'NOIDA',
    },
    {
      _id: '125ajn1k123askn90',
      cityName: 'HYDERABAD',
    },
    {
      _id: '126ajn1k123askn90',
      cityName: 'KARNATAKA',
    },
  ]);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1500);
  }, []);

  if (loading) {
    return <LoadingMessage />;
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>HuntMyParadise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <h2
          style={{
            width: '72%',
            margin: 0,
            marginTop: 24,
            textAlign: 'center',
          }}
        >
          Cities:
        </h2>
        <div className={styles.categoryCities}>
          {cities.map((v) => (
            <div
              key={v._id}
              className={styles.categoryCity}
              style={{
                background:
                  locationFilter === v.cityName ? '#5042a3' : 'mediumslateblue',
              }}
              onClick={() => {
                if (locationFilter === v.cityName) {
                  setLocationFilter('All');
                } else {
                  setLocationFilter(v.cityName);
                }
              }}
              aria-hidden="true"
            >
              <h4>{v.cityName}</h4>
            </div>
          ))}
        </div>
        <h2
          style={{
            width: '72%',
            margin: 0,
            marginTop: 24,
            textAlign: 'center',
          }}
        >
          Filters:
        </h2>
        <div className={styles.filters}>
          <div className={styles.filterItem}>
            <select
              id="filterStar"
              className={styles.filterSelectItem}
              onBlur={(e) => setStarsFilter(e.currentTarget.value)}
            >
              <option defaultValue value="All">
                All Stars
              </option>
              <option value="1">1 star</option>
              <option value="2">2 star</option>
              <option value="3">3 star</option>
              <option value="4">4 star</option>
              <option value="5">5 star</option>
            </select>
          </div>

          <div className={styles.filterItem}>
            <select
              id="filterCost"
              className={styles.filterSelectItem}
              onBlur={(e) => setCostFilter(e.currentTarget.value)}
            >
              <option defaultValue value="All">
                All Cost Ranges
              </option>
              <option value="1">$1,000-$10,000</option>
              <option value="2">$10,000-$20,000</option>
              <option value="3">$20,000-$30,000</option>
              <option value="4">$30,000-$40,000</option>
              <option value="5">$40,000-$50,000</option>
            </select>
          </div>

          <div className={styles.filterItem}>
            <select
              id="filterAmenities"
              className={styles.filterSelectItem}
              onBlur={(e) => setAmenitiesFilter(e.currentTarget.value)}
            >
              <option defaultValue value="All">
                All Amenities
              </option>
              <option>Amenties</option>
              <option>Bedroom</option>
              <option>TV with cable</option>
              <option>Essentially kit</option>
              <option>Towels</option>
              <option>Dining </option>
              <option>Swimming pool</option>
              <option>Parking</option>
              <option>Massage</option>
              <option>Bar & Restraunt</option>
            </select>
          </div>

          <div className={styles.filterItem}>
            <select
              id="filterMember"
              className={styles.filterSelectItem}
              onBlur={(e) => setMemberFilter(e.currentTarget.value)}
            >
              <option defaultValue value="All">
                No. of members
              </option>
              <option>1-4</option>
              <option>5-10</option>
              <option>10-20</option>
              <option>20-50</option>
            </select>
          </div>
        </div>

        <div className={styles.hotelList}>
          {hotels
            .filter(
              (v) => v.location === locationFilter || locationFilter === 'All'
            )
            .filter(
              (v) =>
                v.stars === parseInt(starsFilter, 10) || starsFilter === 'All'
            )
            .filter((v) => v.member === memberFilter || memberFilter === 'All')
            .filter(
              (v) => v.cost === parseInt(costFilter, 10) || costFilter === 'All'
            )
            .map((v) => (
              <div key={v._id} className={styles.hotelItems}>
                <div className={styles.imgContainer}>
                  <img
                    src="http://cdn.cnn.com/cnnnext/dam/assets/190816161527-hotel-views-intercontinental-hong-kong.jpg"
                    alt="hotel view"
                  />
                </div>
                <div className={styles.infoContainer}>
                  <span className={styles.stars}>
                    {Array(v.stars).fill(<Star size={24} color="#ffff00" />)}
                    {Array(5 - v.stars).fill(<Star size={24} color="#aaa" />)}
                  </span>
                  <h3 className={styles.removeSpaces}>{v.hotelName}</h3>
                  <p className={styles.removeSpaces}>{v.viewAmenities}</p>
                </div>
                <div className={styles.linksContainer}>
                  <Link href={`/hotel/${encodeURIComponent(v._id)}`}>
                    <button type="button" className={styles.bookNowButton}>
                      <Calendar /> Book Now
                    </button>
                  </Link>
                  <div className={styles.ratings}>
                    User Ratings:
                    <br /> {v.rating}/5
                  </div>
                </div>
              </div>
            ))}
        </div>
      </main>
    </div>
  );
}
