/* eslint-disable jsx-a11y/label-has-associated-control */
/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react/no-unescaped-entities */
/* eslint-disable react/style-prop-object */
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
// import '../styles/contact.module.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import LoadingMessage from '../components/loading';
import Header from '../components/Header';

export default function Contact() {
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 400);
  }, []);
  if (loading) {
    return <LoadingMessage />;
  }
  return (
    <>
      <Head>
        <title>HuntMyParadise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <style jsx>
          {`
            .codeqwe {
              padding-top: 135px;
              padding-bottom: 90px;
              background-color: #ecfafc;
            }

            .hidden {
              visibility: hidden;
            }

            .mbr-z-index20 {
              z-index: 20;
            }

            .mbr-white {
              color: #ffffff;
            }

            .mbr-black {
              color: #000000;
            }

            .mbr-bg-white {
              background-color: #ffffff;
            }

            .mbr-bg-black {
              background-color: #000000;
            }

            .align-left {
              text-align: left;
            }

            .align-center {
              text-align: center;
            }

            .align-right {
              text-align: right;
            }

            @media (max-width: 767px) {
              .align-left,
              .align-center,
              .align-right,
              .mbr-section-btn,
              .mbr-section-title {
                text-align: center;
              }
            }

            .mbr-light {
              font-weight: 300;
            }

            .mbr-regular {
              font-weight: 400;
            }

            .mbr-semibold {
              font-weight: 500;
            }

            .mbr-bold {
              font-weight: 700;
            }

            .media-size-item {
              -webkit-flex: 1 1 auto;
              -moz-flex: 1 1 auto;
              -ms-flex: 1 1 auto;
              -o-flex: 1 1 auto;
              flex: 1 1 auto;
            }

            .media-content {
              -webkit-flex-basis: 100%;
              flex-basis: 100%;
            }

            .media-container-row {
              display: -ms-flexbox;
              display: -webkit-flex;
              display: flex;
              -webkit-flex-direction: row;
              -ms-flex-direction: row;
              flex-direction: row;
              -webkit-flex-wrap: wrap;
              -ms-flex-wrap: wrap;
              flex-wrap: wrap;
              -webkit-justify-content: center;
              -ms-flex-pack: center;
              justify-content: center;
              -webkit-align-content: center;
              -ms-flex-line-pack: center;
              align-content: center;
              -webkit-align-items: start;
              -ms-flex-align: start;
              align-items: start;
            }

            .media-container-row .media-size-item {
              width: 400px;
            }

            .media-container-column {
              display: -ms-flexbox;
              display: -webkit-flex;
              display: flex;
              -webkit-flex-direction: column;
              -ms-flex-direction: column;
              flex-direction: column;
              -webkit-flex-wrap: wrap;
              -ms-flex-wrap: wrap;
              flex-wrap: wrap;
              -webkit-justify-content: center;
              -ms-flex-pack: center;
              justify-content: center;
              -webkit-align-content: center;
              -ms-flex-line-pack: center;
              align-content: center;
              -webkit-align-items: stretch;
              -ms-flex-align: stretch;
              align-items: stretch;
            }

            .media-container-column > * {
              width: 100%;
            }

            @media (min-width: 992px) {
              .media-container-row {
                -webkit-flex-wrap: nowrap;
                -ms-flex-wrap: nowrap;
                flex-wrap: nowrap;
              }
            }

            figure {
              overflow: hidden;
            }

            figure[mbr-media-size] {
              transition: width 0.1s;
            }

            .mbr-figure img,
            .mbr-figure iframe {
              display: block;
              width: 100%;
            }

            .card {
              background-color: transparent;
              border: none;
            }

            .card-img {
              text-align: center;
              flex-shrink: 0;
            }

            .media {
              max-width: 100%;
              margin: 0 auto;
            }

            .mbr-figure {
              -ms-flex-item-align: center;
              -ms-grid-row-align: center;
              -webkit-align-self: center;
              align-self: center;
            }

            .media-container > div {
              max-width: 100%;
            }

            .mbr-figure img,
            .card-img img {
              width: 100%;
            }

            @media (max-width: 991px) {
              .media-size-item {
                width: auto !important;
              }
              .media {
                width: auto;
              }
              .mbr-figure {
                width: 100% !important;
              }
            }

            .mbr-section-btn {
              margin-left: -0.25rem;
              margin-right: -0.25rem;
              font-size: 0;
            }

            nav .mbr-section-btn {
              margin-left: 0rem;
              margin-right: 0rem;
            }

            .btn .mbr-iconfont,
            .btn.btn-sm .mbr-iconfont {
              cursor: pointer;
              margin-right: 0.5rem;
            }

            .btn.btn-md .mbr-iconfont,
            .btn.btn-md .mbr-iconfont {
              margin-right: 0.8rem;
            }

            .mbr-regular {
              font-weight: 400;
            }

            .mbr-semibold {
              font-weight: 500;
            }

            .mbr-bold {
              font-weight: 700;
            }

            [type='submit'] {
              -webkit-appearance: none;
            }

            .mbr-fullscreen .mbr-overlay {
              min-height: 100vh;
            }

            .mbr-fullscreen {
              display: flex;
              display: -webkit-flex;
              display: -moz-flex;
              display: -ms-flex;
              display: -o-flex;
              align-items: center;
              -webkit-align-items: center;
              min-height: 100vh;
              padding-top: 3rem;
              padding-bottom: 3rem;
            }

            .map {
              height: 25rem;
              position: relative;
            }

            .map iframe {
              width: 100%;
              height: 100%;
            }

            .form-asterisk {
              font-family: initial;
              position: absolute;
              top: -2px;
              font-weight: normal;
            }

            .mbr-arrow-up {
              bottom: 25px;
              right: 90px;
              position: fixed;
              text-align: right;
              z-index: 5000;
              color: #ffffff;
              font-size: 32px;
              transform: rotate(180deg);
              -webkit-transform: rotate(180deg);
            }

            .mbr-arrow-up a {
              background: rgba(0, 0, 0, 0.2);
              border-radius: 3px;
              color: #fff;
              display: inline-block;
              height: 60px;
              width: 60px;
              outline-style: none !important;
              position: relative;
              text-decoration: none;
              transition: all 0.3s ease-in-out;
              cursor: pointer;
              text-align: center;
            }

            .mbr-arrow-up a:hover {
              background-color: rgba(0, 0, 0, 0.4);
            }

            .mbr-arrow-up a i {
              line-height: 60px;
            }

            .mbr-arrow-up-icon {
              display: block;
              color: #fff;
            }

            .mbr-arrow-up-icon::before {
              content: 'aaa';
              display: inline-block;
              font-family: serif;
              font-size: 32px;
              line-height: 1;
              font-style: normal;
              position: relative;
              top: 6px;
              left: -4px;
              -webkit-transform: rotate(-90deg);
              transform: rotate(-90deg);
            }

            .mbr-arrow {
              position: absolute;
              bottom: 45px;
              left: 50%;
              width: 60px;
              height: 60px;
              cursor: pointer;
              background-color: rgba(80, 80, 80, 0.5);
              border-radius: 50%;
              -webkit-transform: translateX(-50%);
              transform: translateX(-50%);
            }

            .mbr-arrow > a {
              display: inline-block;
              text-decoration: none;
              outline-style: none;
              -webkit-animation: arrowdown 1.7s ease-in-out infinite;
              animation: arrowdown 1.7s ease-in-out infinite;
            }

            .mbr-arrow > a > i {
              position: absolute;
              top: -2px;
              left: 15px;
              font-size: 2rem;
            }

            @keyframes arrowdown {
              0% {
                transform: translateY(0px);
                -webkit-transform: translateY(0px);
              }
              50% {
                transform: translateY(-5px);
                -webkit-transform: translateY(-5px);
              }
              100% {
                transform: translateY(0px);
                -webkit-transform: translateY(0px);
              }
            }

            @-webkit-keyframes arrowdown {
              0% {
                transform: translateY(0px);
                -webkit-transform: translateY(0px);
              }
              50% {
                transform: translateY(-5px);
                -webkit-transform: translateY(-5px);
              }
              100% {
                transform: translateY(0px);
                -webkit-transform: translateY(0px);
              }
            }

            @media (max-width: 500px) {
              .mbr-arrow-up {
                left: 50%;
                right: auto;
                transform: translateX(-50%) rotate(180deg);
                -webkit-transform: translateX(-50%) rotate(180deg);
              }
            }

            @keyframes gradient-animation {
              from {
                background-position: 0% 100%;
                animation-timing-function: ease-in-out;
              }
              to {
                background-position: 100% 0%;
                animation-timing-function: ease-in-out;
              }
            }

            @-webkit-keyframes gradient-animation {
              from {
                background-position: 0% 100%;
                animation-timing-function: ease-in-out;
              }
              to {
                background-position: 100% 0%;
                animation-timing-function: ease-in-out;
              }
            }

            .bg-gradient {
              background-size: 200% 200%;
              animation: gradient-animation 5s infinite alternate;
              -webkit-animation: gradient-animation 5s infinite alternate;
            }

            .menu .navbar-brand {
              display: -webkit-flex;
            }

            .menu .navbar-brand span {
              display: flex;
              display: -webkit-flex;
            }

            .menu .navbar-brand .navbar-caption-wrap {
              display: -webkit-flex;
            }

            .menu .navbar-brand .navbar-logo img {
              display: -webkit-flex;
            }

            @media (min-width: 768px) and (max-width: 991px) {
              .menu .navbar-toggleable-sm .navbar-nav {
                display: -webkit-box;
                display: -webkit-flex;
                display: -ms-flexbox;
              }
            }

            @media (min-width: 992px) {
              .menu .navbar-nav.nav-dropdown {
                display: -webkit-flex;
              }
              .menu .navbar-toggleable-sm .navbar-collapse {
                display: -webkit-flex !important;
              }
            }
          `}
        </style>
        <Header />
        <section className="header1 codeqwe">
          <div className="container">
            <div className="row justify-content-md-center">
              <div className="mbr-white col-md-10">
                <h1
                  className="mbr-section-title align-center mbr-bold pb-3 mbr-fonts-style display-5"
                  style={{ color: '#232323' }}
                >
                  Responsive Bootstrap About Us Page Template
                </h1>
                <h3
                  className="mbr-section-subtitle align-center mbr-light pb-3 mbr-fonts-style display-2"
                  style={{ color: '#232323' }}
                >
                  MEET OUR TEAM
                </h3>
                <p
                  className="mbr-text align-center pb-3 mbr-fonts-style display-5"
                  style={{ color: '#232323' }}
                >
                  We are all very different. We were born in different cities,
                  at different times, we love different music, food, movies. But
                  we have something that unites us all. It is our company. We
                  are its heart. We are not just a team, we are a family.
                </p>
                <div className="mbr-section-btn align-center">
                  <a
                    className="btn btn-md btn-black-outline display-4 border border-info"
                    href="index.html#form1-4"
                  >
                    CONTACT US
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>

        <style jsx>{`
          .cid-qyvcqB36eR {
            padding-top: 135px;
            padding-bottom: 135px;
            background-image: url(https://mobirise.com/bootstrap-template/about-us-p…te/assets/images/mitch-rosen-188054-2000x1125.jpg);
          }
        `}</style>
        <section
          className="header1 cid-qyvcqB36eR"
          id="header1-0"
          data-rv-view="761"
        >
          <div className="container">
            <div className="row justify-content-md-center">
              <div className="mbr-white col-md-10" />
            </div>
          </div>
        </section>
        <section
          className="features1 cid-qyvcAqZyNq"
          id="features1-1"
          data-rv-view="764"
        >
          <div className="container">
            <div className="media-container-row">
              <div className="card p-3 col-12 col-md-6 col-lg-4">
                <div className="card-img pb-3">
                  <span
                    className="mbr-iconfont mbri-users"
                    style={{ color: 'rgb(0, 0, 0)' }}
                    media-simple="true"
                  />
                </div>
                <div className="card-box">
                  <h4 className="card-title py-3 mbr-fonts-style display-5">
                    Creativity
                  </h4>
                  <p className="mbr-text mbr-fonts-style display-7">
                    It\'s the ability to think outside the box. We make
                    decisions, create something new and generate a lot of ideas.
                  </p>
                </div>
              </div>

              <div className="card p-3 col-12 col-md-6 col-lg-4">
                <div className="card-img pb-3">
                  <span style={{ color: 'rgb(0, 0, 0)' }} media-simple="true" />
                </div>
                <div className="card-box">
                  <h4 className="card-title py-3 mbr-fonts-style display-5">
                    Worldwide
                  </h4>
                  <p className="mbr-text mbr-fonts-style display-7">
                    All sites you make with Mobirise are mobile-friendly. You
                    don't have to create a special mobile version of your site.
                  </p>
                </div>
              </div>

              <div className="card p-3 col-12 col-md-6 col-lg-4">
                <div className="card-img pb-3">
                  <span
                    className="mbr-iconfont mbri-smile-face"
                    style={{ color: 'rgb(0, 0, 0)' }}
                    media-simple="true"
                  />
                </div>
                <div className="card-box">
                  <h4 className="card-title py-3 mbr-fonts-style display-5">
                    Unique Styles
                  </h4>
                  <p className="mbr-text mbr-fonts-style display-7">
                    Mobirise offers many site blocks in several themes, and
                    though these blocks are pre-made, they are flexible.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section
          className="carousel slide testimonials-slider cid-qyvf5AQs7c"
          id="testimonials-slider1-3"
          data-rv-view="767"
        >
          <div className="container text-center">
            <div
              className="carousel slide"
              data-ride="carousel"
              role="listbox"
              id="testimonials-slider1-3-carousel"
            >
              <div className="carousel-inner">
                <div className="carousel-item">
                  <div className="user col-md-8">
                    <div className="user_image">
                      <img
                        src="assets/images/mike-wilson-253599-2189x2189.jpg"
                        alt=""
                        title=""
                        media-simple="true"
                      />
                    </div>
                    <div className="user_text pb-3">
                      <p className="mbr-fonts-style display-7">
                        Good afternoon. I am very pleased with the quality of
                        the work of your employee representing your wonderful
                        company.
                      </p>
                    </div>
                    <div className="user_name mbr-bold pb-2 mbr-fonts-style display-7">
                      Helen
                    </div>
                    <div className="user_desk mbr-light mbr-fonts-style display-7">
                      DESIGNER
                    </div>
                  </div>
                </div>
                <div className="carousel-item">
                  <div className="user col-md-8">
                    <div className="user_image">
                      <img
                        src="assets/images/ayo-ogunseinde-316141-3333x3333.jpg"
                        alt=""
                        title=""
                        media-simple="true"
                      />
                    </div>
                    <div className="user_text pb-3">
                      <p className="mbr-fonts-style display-7">
                        All issues are resolved promptly. In communication, the
                        employees are pleasant, helpful. Always offer new ideas,
                        new ways to develop, improve our project.
                      </p>
                    </div>
                    <div className="user_name mbr-bold pb-2 mbr-fonts-style display-7">
                      Linda
                    </div>
                    <div className="user_desk mbr-light mbr-fonts-style display-7">
                      DEVELOPER
                    </div>
                  </div>
                </div>
                <div className="carousel-item active">
                  <div className="user col-md-8">
                    <div className="user_image">
                      <img
                        src="assets/images/yoann-boyer-316485-1333x1333.jpg"
                        alt=""
                        title=""
                        media-simple="true"
                      />
                    </div>
                    <div className="user_text pb-3">
                      <p className="mbr-fonts-style display-7">
                        Excellent client manager. He is always accurate, all
                        promises are fulfilled, all questions get answers, the
                        company presents very attentive and positive approach.
                      </p>
                    </div>
                    <div className="user_name mbr-bold pb-2 mbr-fonts-style display-7">
                      Linda
                    </div>
                    <div className="user_desk mbr-light mbr-fonts-style display-7">
                      DEVELOPER
                    </div>
                  </div>
                </div>
              </div>

              <div className="carousel-controls">
                <a
                  className="carousel-control-prev"
                  role="button"
                  data-slide="prev"
                  href="#testimonials-slider1-3-carousel"
                >
                  <span
                    aria-hidden="true"
                    className="mbri-arrow-prev mbr-iconfont"
                  />
                  <span className="sr-only">Previous</span>
                </a>

                <a
                  className="carousel-control-next"
                  role="button"
                  data-slide="next"
                  href="#testimonials-slider1-3-carousel"
                >
                  <span
                    aria-hidden="true"
                    className="mbri-arrow-next mbr-iconfont"
                  />
                  <span className="sr-only">Next</span>
                </a>
              </div>
            </div>
          </div>
        </section>
        <section
          className="clients cid-qyvf5b5WEt"
          id="clients-2"
          data-rv-view="777"
        >
          <div className="container mb-5">
            <div className="media-container-row">
              <div className="col-12 align-center">
                <h2 className="mbr-section-title pb-3 mbr-fonts-style display-2">
                  Our Clients
                </h2>
                <h3 className="mbr-section-subtitle mbr-light mbr-fonts-style display-5">
                  Thank you for choosing us!
                </h3>
              </div>
            </div>
          </div>

          <div className="container">
            <div
              className="carousel slide"
              data-ride="carousel"
              role="listbox"
              id="clients-2-carousel"
            >
              <div className="carousel-inner slides5" data-visible="5">
                <div className="carousel-item">
                  <div className="media-container-row">
                    <div className="col-md-12 col-lg-15">
                      <div className="wrap-img ">
                        <img
                          src="assets/images/1.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-1 clonedCol"
                      data-cloned-index="1"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/2.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-2 clonedCol"
                      data-cloned-index="2"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/3.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-3 clonedCol"
                      data-cloned-index="3"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/4.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-4 clonedCol"
                      data-cloned-index="4"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/5.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="carousel-item">
                  <div className="media-container-row">
                    <div className="col-md-12 col-lg-15">
                      <div className="wrap-img ">
                        <img
                          src="assets/images/2.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-1 clonedCol"
                      data-cloned-index="2"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/3.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-2 clonedCol"
                      data-cloned-index="3"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/4.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-3 clonedCol"
                      data-cloned-index="4"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/5.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-4 clonedCol"
                      data-cloned-index="0"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/1.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="carousel-item">
                  <div className="media-container-row">
                    <div className="col-md-12 col-lg-15">
                      <div className="wrap-img ">
                        <img
                          src="assets/images/3.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-1 clonedCol"
                      data-cloned-index="3"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/4.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-2 clonedCol"
                      data-cloned-index="4"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/5.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-3 clonedCol"
                      data-cloned-index="0"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/1.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-4 clonedCol"
                      data-cloned-index="1"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/2.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="carousel-item">
                  <div className="media-container-row">
                    <div className="col-md-12 col-lg-15">
                      <div className="wrap-img ">
                        <img
                          src="assets/images/4.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-1 clonedCol"
                      data-cloned-index="4"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/5.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-2 clonedCol"
                      data-cloned-index="0"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/1.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-3 clonedCol"
                      data-cloned-index="1"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/2.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-4 clonedCol"
                      data-cloned-index="2"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/3.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                  </div>
                </div>
                <div className="carousel-item active">
                  <div className="media-container-row">
                    <div className="col-md-12 col-lg-15">
                      <div className="wrap-img ">
                        <img
                          src="assets/images/5.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-1 clonedCol"
                      data-cloned-index="0"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/1.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-2 clonedCol"
                      data-cloned-index="1"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/2.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-3 clonedCol"
                      data-cloned-index="2"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/3.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                    <div
                      className="col-md-12 col-lg-15 cloneditem-4 clonedCol"
                      data-cloned-index="3"
                    >
                      <div className="wrap-img ">
                        <img
                          src="assets/images/4.png"
                          className="img-responsive clients-img"
                          media-simple="true"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="carousel-controls">
                <a
                  data-app-prevent-settings=""
                  className="carousel-control carousel-control-prev"
                  role="button"
                  data-slide="prev"
                  href="#clients-2-carousel"
                >
                  <span aria-hidden="true" className="mbri-left mbr-iconfont" />
                  <span className="sr-only">Previous</span>
                </a>
                <a
                  data-app-prevent-settings=""
                  className="carousel-control carousel-control-next"
                  role="button"
                  data-slide="next"
                  href="#clients-2-carousel"
                >
                  <span
                    aria-hidden="true"
                    className="mbri-right mbr-iconfont"
                  />
                  <span className="sr-only">Next</span>
                </a>
              </div>
            </div>
          </div>
        </section>
        <section
          className="mbr-section form1 cid-qyvf9K0GGo"
          id="form1-4"
          data-rv-view="791"
        >
          <div className="container">
            <div className="row justify-content-center">
              <div className="title col-12 col-lg-8">
                <h2 className="mbr-section-title align-center pb-3 mbr-fonts-style display-2">
                  CONTACT US
                </h2>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row justify-content-center">
              <div
                className="media-container-column col-lg-8"
                data-form-type="formoid"
              >
                <div data-form-alert="" hidden="">
                  Thanks for filling out the form!
                </div>

                <form
                  className="mbr-form"
                  action="https://mobirise.com/"
                  method="post"
                  data-form-title="Mobirise Form"
                >
                  <input
                    type="hidden"
                    data-form-email="true"
                    value="R46ImfT8lRYLhZq6vpVE63L0V35bOdmwHjgn18Tp/HdDujD3JfWe/8bm7YjE2vjZZ7JFQMRNRIinYQUh3aNa2qi1GshxArFhHAffNuiFsZiNLfMCF8KElmS7V7lbqBIL"
                  />
                  <div className="row row-sm-offset">
                    <div className="col-md-4 multi-horizontal" data-for="name">
                      <div className="form-group">
                        <label
                          className="form-control-label mbr-fonts-style display-7"
                          htmlFor="name-form1-4"
                        >
                          Name
                        </label>
                        <input
                          type="text"
                          className="form-control"
                          name="name"
                          data-form-field="Name"
                          required=""
                          id="name-form1-4"
                        />
                      </div>
                    </div>
                    <div className="col-md-4 multi-horizontal" data-for="email">
                      <div className="form-group">
                        <label
                          className="form-control-label mbr-fonts-style display-7"
                          htmlFor="email-form1-4"
                        >
                          Email
                        </label>
                        <input
                          type="email"
                          className="form-control"
                          name="email"
                          data-form-field="Email"
                          required=""
                          id="email-form1-4"
                        />
                      </div>
                    </div>
                    <div className="col-md-4 multi-horizontal" data-for="phone">
                      <div className="form-group">
                        <label
                          className="form-control-label mbr-fonts-style display-7"
                          htmlFor="phone-form1-4"
                        >
                          Phone
                        </label>
                        <input
                          type="tel"
                          className="form-control"
                          name="phone"
                          data-form-field="Phone"
                          id="phone-form1-4"
                        />
                      </div>
                    </div>
                  </div>
                  <div className="form-group" data-for="message">
                    <label
                      className="form-control-label mbr-fonts-style display-7"
                      htmlFor="message-form1-4"
                    >
                      Message
                    </label>
                    <textarea
                      type="text"
                      className="form-control"
                      name="message"
                      rows="7"
                      data-form-field="Message"
                      id="message-form1-4"
                    />
                  </div>

                  <span className="input-group-btn">
                    <button
                      href=""
                      type="submit"
                      className="btn btn-form btn-black-outline display-4"
                    >
                      SEND FORM
                    </button>
                  </span>
                </form>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
