import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import JumboWelcome from '../components/JumboWelcome';

function LoadingMessage() {
  return (
    <div className={styles.splashScreen}>
      <img
        src="https://i.pinimg.com/originals/ae/51/e1/ae51e1395e87cc72c6021df5445cc5f8.gif"
        alt="loadingScreen"
      />
    </div>
  );
}

export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1500);
  }, []);

  if (loading) {
    return LoadingMessage();
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>HuntMyParadise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <JumboWelcome />
      </main>
    </div>
  );
}
