import React from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { Star } from 'react-feather';
import { Carousel, Col, Container, Image, Row, Table } from 'react-bootstrap';
import styles from '../../styles/hotelView.module.css';
import Header from '../../components/Header';
import 'bootstrap/dist/css/bootstrap.min.css';

const Hotel = () => {
  const router = useRouter();
  const { hid } = router.query;

  return (
    <div className={styles.container}>
      <Head>
        <title>HuntMyParadise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div className={styles.innercontainer}>
          <br />
          <br />
          <br />
          <Row className="justify-content-md-center mb-4">
            <Col md={12}>
              <h4>Hotel Details:</h4>
            </Col>
            <Col className={styles.hotelImage}>
              <img
                src="https://image.shutterstock.com/image-illustration/hotel-sign-stars-3d-illustration-260nw-195879770.jpg"
                alt="hotel front"
                className=""
              />
            </Col>
            <Col className={styles.hotelDetails}>
              <div>{Array(5).fill(<Star size="24" color="yellow" />)}</div>
              <h3>Hotel Name</h3>
              <em>Code: {hid}</em>
              <p>
                <b>Location:</b> hotel image, Purnima, Kalyan, Maharashtra
                421301
              </p>
              <p>
                Go to <a href="#ownerDetails">Owner Details</a>
              </p>
            </Col>
          </Row>
          <Row className="justify-content-md-center my-4">
            <Col md={12}>
              <h4 className="text-center">Room Photos:</h4>
            </Col>
            <Col md={8} className={styles.imageView}>
              <Carousel>
                <Carousel.Item interval={1000}>
                  <img
                    className="d-block w-100 img-fluid h-100"
                    style={{
                      objectFit: 'contain',
                      minHeight: 400,
                      maxHeight: 400,
                    }}
                    src="http://cdn.home-designing.com/wp-content/uploads/2018/05/stylish-mid-century-style-green-living-room.jpg"
                    alt="First slide"
                  />
                  <Carousel.Caption>
                    <h3>First slide label</h3>
                    <p>
                      Nulla vitae elit libero, a pharetra augue mollis interdum.
                    </p>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                  <img
                    className="d-block w-100 img-fluid h-100"
                    style={{
                      objectFit: 'contain',
                      minHeight: 400,
                      maxHeight: 400,
                    }}
                    src="https://images.squarespace-cdn.com/content/v1/5ef4749fcb87f82095e78538/1595789644804-P7286T96IFDDG3T3M7CN/Farrow+and+Ball+Green+Smoke+walls+with+habitat+velvet+orange+sofa?format=1000w"
                    alt="Second slide"
                  />
                  <Carousel.Caption>
                    <h3>Second slide label</h3>
                    <p>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    </p>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                  <img
                    className="d-block w-100 img-fluid"
                    style={{
                      objectFit: 'contain',
                      minHeight: 400,
                      maxHeight: 400,
                    }}
                    src="https://media.istockphoto.com/photos/empty-minimalist-room-with-gray-wall-on-background-picture-id1129813604?k=20&m=1129813604&s=612x612&w=0&h=FrADrPmofSeBG1T0o5YefRviG_5fq0oDPZosUq84Ax0="
                    alt="Third slide"
                  />
                  <Carousel.Caption>
                    <h3>Third slide label</h3>
                    <p>
                      Praesent commodo cursus magna, vel scelerisque nisl
                      consectetur.
                    </p>
                  </Carousel.Caption>
                </Carousel.Item>
                <Carousel.Item>
                  <img
                    className="d-block w-100 img-fluid h-auto"
                    style={{
                      objectFit: 'cover',
                      minHeight: 400,
                      maxHeight: 400,
                    }}
                    src="https://cdn.vox-cdn.com/thumbor/C7bLRvxNo4r1HWCzy_ajpSv3y6k=/1400x0/filters:no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/20651645/iStock_950319398.jpg"
                    alt="Third slide"
                  />
                  <Carousel.Caption>
                    <h3>Fourth slide label</h3>
                    <p>
                      Praesent commodo cursus magna, vel scelerisque nisl
                      consectetur.
                    </p>
                  </Carousel.Caption>
                </Carousel.Item>
              </Carousel>
            </Col>
          </Row>
          <div>
            <Table striped bordered hover>
              <tbody>
                <tr>
                  <td colSpan="2">
                    Transaction Type: <b>Resale</b>
                  </td>
                  <td colSpan="2">
                    Property Ownership: <b>Freehold</b>
                  </td>
                  <td colSpan="2">
                    Flooring: <b>Marble</b>
                  </td>
                </tr>
                <tr>
                  <td colSpan="2">
                    WheelChair Friendly: <b>Yes</b>
                  </td>
                  <td colSpan="2">
                    Property Code: <b>Q57854574</b>
                  </td>
                  <td colSpan="2">
                    Quality Rating: <b>4</b>
                  </td>
                </tr>
              </tbody>
            </Table>
          </div>
          <div>
            <h3>About Property</h3>
            <p>
              Located in the heart of the city, just few steps away from the
              main bus stand , this is the only resort hotel in katra region. A
              luxury combined with warm and traditional hospitality is what
              makes this hotel popular among both the business and leisure
              traveller
              <br />
              Hotel devi grand is the premier resort hotel in katra region.
              <br />
              Conveniently located in the heart of the city, it is just a few
              steps away from the main bus stand. 70 guest rooms and suites
              offering comforts, executive banquet complemented by a private
              lounge , abundant landscaped gardens, outstanding recreational
              facilities, and excellent service make the this hotel a preferred
              choice for both the business and leisure traveller.
              <br />
              Guests at the devi grand can choose from a wide array of
              restaurants offering a variety of cuisines. From the royal
              continental to the long feng with its chinese and szechuan
              delicacies and spicy north indian food, this hotel can satisfy
              even the most discerning connoisseur. Along with a banquet hall &
              confrence hall
              <br />
              The recreational and leisure facilities over here includes an
              outdoor swimming pool, a fully equipped gymnasium, and more. The
              wellness facility features one of katras best spas offering
              ayurvedic treatments and shiatsu massages to rejuvenate the
              stressful body.
            </p>
            <p>Room service : 24hrs butler service at your bed side</p>
          </div>
          <br />
          <h2>Owner Details</h2>
          <Row id="ownerDetails">
            <Col md={4} className={styles.imageCenter}>
              <Image
                src="https://static.99acres.com/images/owner_pnava.png"
                alt="contact"
                className="mx-auto"
                roundedCircle
              />
            </Col>
            <Col md={8}>
              <Table striped bordered hover size="sm">
                <tbody>
                  <tr>
                    <td colSpan="2">Information:</td>
                  </tr>
                  <tr>
                    <td>Name</td>
                    <td>John Doe</td>
                  </tr>
                  <tr>
                    <td>Place</td>
                    <td>Mumbai</td>
                  </tr>
                  <tr>
                    <td>Phone</td>
                    <td>9890989898</td>
                  </tr>
                  <tr>
                    <td>Verified</td>
                    <td>Yes</td>
                  </tr>
                </tbody>
              </Table>
            </Col>
          </Row>
          <br />
          <br />
          <br />
          <br />
          <br />
        </div>
      </main>
    </div>
  );
};
export default Hotel;
